### ISSUE TITLE
Navigation Stack Issues

### ISSUE THREAD

**Issue by csmltd** [yuzoolcode/yuzoolthemes-tracking#28]
Hi Guys

I have two issues with the Navigation stack.

The first is connected with a continuous error being reported in my developer console.

The attached screenshot should provide the details for you.

The error appears on every page that the Nav stack is installed on.

Navigation Stack Error.png

The second issue is that each time a page loads there is a 1 second delay where all links appear on the screen before final rendering.

Other developers are also experiencing the same issue and none of us are able to isolate where the problem may be.

The only common denominator is that the Nav stack is in use and displays the behaviour on every page each of us have the stack on.

I look forward to hearing from you shortly.

Kind Regards
Paul Rowe

![Navigation Stack Error](https://user-images.githubusercontent.com/51753168/59361014-622a7200-8d5b-11e9-8065-ecd5c8676138.png)

**Comment by yuzoolcode** [comment]
- do you have a link to a site?
- the errors might not be a problem if the site is working. That is to do with Google Fonts and might be occurring as your theme or another Stack may also be loading Google Fonts
- not sure on the 1 second delay and haven't seen that but Nav Stack does have a load later option to prevent loading links before the page has loaded:

![CleanShot 2019-06-13 at 08 45 26](https://user-images.githubusercontent.com/4608547/59393706-ab101400-8db7-11e9-88b7-6e54fcc0ed5e.jpg)

**Comment by csmltd** [comment]
Hi Michael

Thank you for your response.

The Nav stack can be viewed at the following url : https://csmltd.com/

As I serve only my own warehoused fonts the referenced fonts in the previous screenshot represent those fonts that are choices within the Nav stack settings.

I and others have played with the setting referenced in point 3 but alas nothing seemed to work.

I look forward to hearing from you shortly.

Kind Regards
Paul

**Comment by yuzoolcode** [comment]
Sorry, I don't really understand the bug.. the page loads fine for me..

I'm also not quite sure who the "others" are but will need more details.

When it was discussed in the forum, we fixed it up:
https://forums.realmacsoftware.com/t/fixed-load-behavior-from-yuzool-navigation-stack/24248/27

For further refinement, I suggest adding the "fade in animation" option and this will load it a second or so after the page has loaded. That way if there is a theme/stack issue it will be rectified this way.

**Comment by csmltd** [comment]
Hi Michael

Whilst I test the Lazy Loading and "Fade In animation" options to see if that resolves the flash of url lists on the left hand side of the page during loading can you please advise how we can correct the error console reporting issues shown in the screenshot.

The 'others' I was referring to were some attendees of Marten Claridges workshops that he hosts each week. They too were discussing the very same issues that I have raised here for you.

I look forward to hearing from you shortly.

Kind Regards
Paul

**Comment by yuzoolcode** [comment]
I love Marten - thanks for sharing!

Feel free to open a discussion on his site, I have a category on there:
https://forum.rw4all.com/c/yuzoolthemes

Please let me know how testing goes.

As for the errors, what if you select "theme" and don't use the Stack's GFonts?

**Comment by csmltd** [comment]
Hi Michael

As per your suggestion I enabled "Theme" in the font selector but still receive a console warning as per the attached screenshot.

I look forward to hearing from you shortly.

Kind Regards
Paul
![Navigation-console-error](https://user-images.githubusercontent.com/51753168/59482800-96ee1480-8e94-11e9-9024-22b7feb1d415.png)

**Comment by yuzoolcode** [comment]
Thanks Paul

It doesn't exist on the demo page (http://demo.yuzoolthemes.com/navigation/) so it must be a clash with something

That said, it's only a warning and nothing is broken on the page so I wouldn't worry about it 👍
